.eslintrc
.prettierignore
.prettierrc
.travis.yml
package.json
public/index.html
src/client/App.css
src/client/App.js
src/client/Client.js
src/client/Home.js
src/client/NotFound.js
src/client/Projects.js
src/client/Projects.test.js
src/client/components/BreacrumbNav.test.js
src/client/components/BreadcrumbNav.js
src/client/components/Quarter.js
src/client/components/Quarter.test.js
src/client/const.js
src/client/const.test.js
src/client/utils.js
src/client/utils.test.js
src/server/ghapi.js
src/server/index.js
src/server/index.test.js
src/server/queries/getProjects.js
src/server/queries/getTeam.js
src/setupTests.js
yarn.lock

Setup prettier

---

src/client/App.js
src/client/Client.js
src/client/Contrib.js
src/client/Contrib.test.js
src/client/ContribGoodFirstBugs.js
src/client/ContribMaybeGoodFirstBugs.js
src/client/ContribWelcome.js
src/client/Milestones.js
src/fixtures/contribWelcome.js
src/server/ghapi.js
src/server/index.js
src/server/queries/getContribWelcome.js
src/setupTests.js

Fixes #89
Each contrib view loads its own data now, and this also adds `contrib: welcome` issues.

Refactor contrib and add contrib welcome issues

---

src/server/queries/getContribWelcome.js
src/server/queries/getGoodFirstBugs.js
src/server/queries/getMaybeGoodFirstBugs.js
src/server/queries/utils.js

Fixes #150
This adds the missing repo and switches to a common var that defines all repos.

Add addons-code-manager to contrib views

---

src/client/Milestones.js

Update latest url and preserve QS

---

src/client/Milestones.js
src/setupTests.js

Scroll to top on data changes for milestones

---

package.json
src/client/Client.test.js
src/client/utils.js
src/server/index.js
src/server/index.test.js
yarn.lock

Some small improvements to test coverage.

Improve test coverage and remove unecessary markdown dep

---

src/client/Milestones.js
src/client/Milestones.scss
src/fixtures/milestoneIssues.js
src/server/queries/getMilestoneIssues.js

Show all reviewers who approved the PR for each issue.

Show issue reviewers

---

src/client/Milestones.js
src/client/Milestones.scss
src/fixtures/milestoneIssues.js
src/server/queries/getMilestoneIssues.js

Fixes #187
Before:
width="1405" alt="Milestones_-_Add-ons_PM" src="https://user-images.githubusercontent.com/1514/67794209-32fb6f80-fa74-11e9-9034-128890ec3c9c.png">
After:

De dupe reviewer column

---

src/client/Milestones.js

Fixes #190 
Fixes #189
This moves calculating reviewers into the formatData function so it only happens when data is returned rather than on every render. This facilitates making the basic sort functions system work too.

Fix reviewer sort and external links

---

.travis.yml

Add node 12 and remove node 8 from travis

---

src/client/Projects.js
src/client/Projects.test.js

Fix logic bug in getNextQuarter()

---

src/client/Milestones.js

Fix missing review

---

src/client/App.scss
src/client/Dashboard.scss
src/client/Milestones.js
src/client/Projects.js

Add sticky table headers and headings

---

src/client/Dashboard.scss
src/client/DashboardWE.js
src/client/DashboardWE.scss

Fix font size

---

src/client/Projects.js

Fix percentages for 0 cards

---

pages/api/gh-contrib-welcome.js
pages/api/gh-good-first-bugs.js
pages/api/gh-maybe-good-first-bugs.js

Fix queries for contrib

---

.gitignore
components/Contrib.js
components/Engineer.js
package.json
pages/_app.js
pages/milestones/[milestone].js
pages/projects/[year]/[quarter].js
styles/globals.scss
yarn.lock

This combines two dep updates with some tweaks (hacks) to keep the look and feel closer to what we had with bootstrap 4.

React bootstrap 2

---

pages/milestones/index.js
pages/milestones/latest.js
pages/projects/index.js
pages/projects/latest.js
tests/pages/milestones/index.test.js
tests/pages/milestones/latest.test.js
tests/pages/projects/index.test.js

Fix index redirs

---

.circleci/config.yml

Replace legacy circleci convenience image for Node with modern one

---

package.json
tests/components/ActiveLink.test.js
tests/components/HeaderLink.test.js
tests/pages/contrib/contrib-welcome.test.js
tests/pages/contrib/good-first-bugs.test.js
tests/pages/contrib/maybe-good-first-bugs.test.js
tests/pages/dashboards/amo.test.js
tests/pages/dashboards/webext.test.js
tests/pages/milestones/[milestone].test.js
tests/pages/projects/[year]/[quarter].test.js
yarn.lock

This should fix the build with next.js v12.1.5+

Switch next router mocking to next-router-mock
